import Head from "next/head";

type Props = {
  title?: string;
  children: React.ReactNode;
};

const Container = ({ title = "Home", children }: Props) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full max-w-5xl px-4 mx-auto my-10 antialiased sm:px-6 md:my-12 lg:px-8">
        {children}
      </main>
    </>
  );
};

export default Container;
