import Head from "next/head";
import Header from "~/components/Header";
import Footer from "~/components/Footer";

type Props = {
  title?: string;
  children: React.ReactNode;
};

const Container = ({ title = "Home", children }: Props) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="w-full max-w-6xl px-4 mx-auto my-16 antialiased sm:px-6 md:my-20 lg:px-8">
        {children}
      </main>
      <Footer />
    </>
  );
};

export default Container;
